/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                  '#006b2d',
        'primary-container':        '#00873b',
        'primary-fixed':            '#83fb9b',
        'primary-fixed-dim':        '#67de81',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#f7fff3',
        'on-primary-fixed':         '#002109',
        'on-primary-fixed-variant': '#005321',
        'inverse-primary':          '#67de81',
        'secondary':                '#565e74',
        'secondary-fixed':          '#dae2fd',
        'secondary-fixed-dim':      '#bec6e0',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#5c647a',
        'on-secondary-fixed':       '#131b2e',
        'on-secondary-fixed-variant':'#3f465c',
        'secondary-container':      '#dae2fd',
        'tertiary':                 '#555d64',
        'tertiary-container':       '#6e757d',
        'tertiary-fixed':           '#dce3ec',
        'tertiary-fixed-dim':       '#c0c7d0',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#fcfcff',
        'on-tertiary-fixed':        '#151c23',
        'on-tertiary-fixed-variant':'#40484f',
        'error':                    '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        'background':               '#f5fbf0',
        'on-background':            '#171d17',
        'surface':                  '#f5fbf0',
        'surface-dim':              '#d5dcd1',
        'surface-bright':           '#f5fbf0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#eff6eb',
        'surface-container':        '#e9f0e5',
        'surface-container-high':   '#e3eadf',
        'surface-container-highest':'#dee5da',
        'on-surface':               '#171d17',
        'on-surface-variant':       '#3e4a3e',
        'surface-variant':          '#dee5da',
        'surface-tint':             '#006e2f',
        'inverse-surface':          '#2b322b',
        'inverse-on-surface':       '#ecf3e8',
        'outline':                  '#6e7a6d',
        'outline-variant':          '#bdcaba',
        'wa':                       '#25D366',
      },
      fontFamily: {
        sans:           ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
        'jakarta':      ['Plus Jakarta Sans', 'sans-serif'],
        'inter':        ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }],
        'h2':      ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h3':      ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'price':   ['28px', { lineHeight: '1', fontWeight: '800' }],
        'label':   ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: { container: '1280px' },
    },
  },
  plugins: [],
}
